### ISSUE TITLE
mapping errors doesn't work as I expected (but maybe it's as intended?)

### ISSUE THREAD

**Issue by rogierschouten** [poelstra/ts-stream#33]
My intention is to map 'foo' errors to 'bar' errors using `Stream#map()`.

However whenever you assign an error handler to the `Stream#map()` function, two things happen:
1. it results in unhandled rejections of the mapped error
1. the original is passed on to the writable instead of the mapped one

Code:
```javascript
var tsstream = require("ts-stream");

process.on("unhandledRejection", (error) => console.log("unhandled:", error));

var s = new tsstream.Stream();

var t = s
	.map(
		(v) => {
			return Promise.reject(new Error("foo")); // generate an error
		},
		(e) => {
			return Promise.reject(new Error("bar")); // map error
		});

s.write("a")
	.then(() => s.end())
	.catch((e) => s.end(e));

t.forEach((v) => console.log(v))
	.catch((e) => console.log("caught", e));

setTimeout(() => undefined, 1000);
```

Output:
```sh
caught Error: foo
    at s.map (C:\Source\modules\exlent-exlent\temp.js:10:26)
    at C:\Source\modules\xit-workspace-modules\ts-stream\1.0.1\dist\lib\Transform.js:46:46
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
unhandled: Error: bar
    at s.map (C:\Source\modules\exlent-exlent\temp.js:13:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
```

**Comment by rogierschouten** [comment]
Please note: the uncaught error is due to the `s.end()` calls not being handled. So one of the issues is clear.

**Comment by poelstra** [comment]
I'm not 100% sure what you're trying to achieve, but I suppose you expect that if you *return* an error from `map()`, that it would be *forwarded* to the next block in the pipeline. This is not the intended behavior indeed.

Intended behavior is that any error that is thrown is always 'bounced back' to the sender, in this case your `end()` call.

Additionally, something has to be done to make the total stream end, even though the ender itself apparently failed, too (because it returned a rejection). The current implementation (see https://github.com/poelstra/ts-stream/blob/666b6698a1632a4eabe9f66071d0834d769a5238/src/lib/Transform.ts#L47) will pass on the error it received, then an error from the map, if any.

Of course, in case of seeing two errors, it's a bit arbitrary to define which should take preference. I did not want to introduce some kind of `AggregateError`, and it seemed more sensible to forward the original error, given that a failure in map's ender might be some kind of follow-up error.

In your case, I suggest using e.g. `transform()`, and doing something like:
```ts
var tsstream = require("ts-stream");

process.on("unhandledRejection", (error) => console.log("unhandled:", error));

var s = new tsstream.Stream();

function remap(readable, writable) {
	writable.aborted().catch((e) => readable.abort(e));
	readable.aborted().catch((e) => writable.abort(e));
	readable.forEach(
		(v) => writable.write(v),
		(e) => {
			if (e) {
				e = new Error("remapped error");
			}
			return writable.end(e, readable.result());
		}
	);
}

var t = s.transform(remap)

// End stream with an error
s.end(new Error("foo")).catch(() => {});

t.forEach((v) => console.log(v))
	.catch((e) => console.log("caught", e));

setTimeout(() => undefined, 1000);
```

This outputs:
```
caught Error: remapped error
    at readable.forEach (/home/martin/src/ts-stream/test.js:14:9)
    at /home/martin/src/ts-stream/dist/lib/Stream.js:656:98
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
