### ISSUE TITLE
Add "pause" support.

### ISSUE THREAD

**Issue by martinheidegger** [poelstra/ts-stream#36]
It is possible to pause node streams. I think it would be a good idea to allow ts-streams to be paused as well. My thinking is to add a 4th property to the "forEach" method:

```typescript
forEach: (
  reader: (item: Uint8Array) => PromiseLike<void> | void,
  ender?: (error?: Error) => void,
  aborter?: (error: Error) => void,
  pauser?: (isPaused: boolean) => void
): Promise<void> => { }
```

**Comment by poelstra** [comment]
Pausing of node streams is necessary because there's no other way to provide backpressure (e.g. when using `on("data", ...)`). Note that one way to pause streams is to pass a promise from your reader that only resolves when you want the stream to continue.

What is the use-case you want to solve with this?

BTW, I'm not sure why there would need to be a `pauser`. I would think pausing would be handled completely transparently (i.e. internally) to the end-user?

**Comment by martinheidegger** [comment]
It is my thinking that a user-interface could use this info to display streams as paused or running. I havn't thought about it as solution for back-pressure.

I was aware that this could be implemented using a promise but that would make it necessary to implement that logic in every implementation of a stream. _(Seems like the library ought to do that)_

It might also be useful in case one wants to deliberately pause the current effort.

**Comment by poelstra** [comment]
In that case, I'd suggest to create a transform that does just that. (Could even be a `map`.)
That way, you can make any stream 'pauseable', and have any kind of feedback to the UI you want (including passing how many packets per second etc).

**Comment by martinheidegger** [comment]
_(_ 🤔 _I am rarely flabbergasted by other persons ideas being so much better than my own. )_

That is not just a fair point, that is a really good idea and approach. Like it much better than my own 😄
